# -*- coding: utf-8 -*-
"""california.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZE9OGhHMtMDoADrRijU2akPj1MaN_S4
"""

from sklearn.neural_network import MLPRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

housing = fetch_california_housing()
X, y= housing.data, housing.target

#Explora los datos
type(housing)
housing.keys()
housing['data']
housing['target']
housing['target_names']
housing['DESCR']
housing['feature_names']

# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Escalar las carecteristicas para un mejor rendimiento del modelo
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#Crear una instancia de MLPregressor
mlp_reg = MLPRegressor(hidden_layer_sizes=(100,), activation='relu', solver='adam', random_state=42, verbose=True)

#Entrenar el modelo
mlp_reg.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = mlp_reg.predict(X_test)

# Calcular el error cuadratico medio del modelo
mse = mean_squared_error(y_test, y_pred)
print("Error cuadratico medio del modelo:", mse)

import pandas as pd

df_housing = pd.DataFrame(X, columns=housing.feature_names)
df_housing['MedHouseVal'] = y

display(df_housing.head())