# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CW147APERsPdDNPzkzvEnTERT7Twfr--
"""

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

import pandas as pd
from sklearn.datasets import load_iris

# Cargar los datos de iris si no están cargados
iris = load_iris()
X, y = iris.data, iris.target

df_iris = pd.DataFrame(X, columns=iris.feature_names)
display(df_iris.head())

#conjunto de datos
iris = load_iris()
X, y = iris.data, iris.target

#Explorar los datos
type(iris)
iris.keys()
iris['data']
iris['target']
iris['target_names']
iris['DESCR']
iris['feature_names']

#dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

mlp_clf = MLPClassifier(hidden_layer_sizes=(100), activation='relu', solver='adam', max_iter=100, random_state=42,verbose=True)

mlp_clf.fit(X_train_scaled, y_train)

y_pred = mlp_clf.predict(X_test_scaled)
print(y_test)
print(y_pred)

accuracy=accuracy_score(y_test,y_pred)
print("Precision del modelo",accuracy)