# -*- coding: utf-8 -*-
"""MNIST.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YgTYUNfBWjySsaO90OgTlEgCjkz01m_p
"""

import keras
mnist = keras.datasets.mnist
(training_images, training_labels), (test_images, test_labels) = mnist.load_data()

import numpy as np
import matplotlib.pyplot as plt
index = 1
np.set_printoptions(linewidth=320)
print(f'Label:{training_labels[index]}')
print(f'Image:{training_images[index]}')

plt.imshow(training_images[index])

training_images = training_images / 255.0
test_images = test_images / 255

model = keras.models.Sequential([keras.layers.Flatten(input_shape = (28, 28)), keras.layers.Dense(128, activation ='relu'), keras.layers.Dense(10, activation = 'softmax')])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(training_images, training_labels, epochs = 10)

import pandas as pd
pd.DataFrame(history.history).plot(grid=True)

loss, accuracy = model.evaluate(training_images, training_labels)
print("Perdida en el conjunto de entrenamiento:", loss)
print("Precision en el conjunto de entrenamiento:", accuracy)

loss, accuracy = model.evaluate(test_images, test_labels)
print("Perdida en el conjunto de prueba:", loss)
print("Precision en el conjunto de prueba:", accuracy)

loss, accuracy = model.evaluate(test_images, test_labels)
print("Perdida en el conjunto de prueba:", loss)
print("Precision en el conjunto de prueba:", accuracy)