# -*- coding: utf-8 -*-
"""NetflixDataSet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0vkuV6DtykQkJkPX3tliN92LFDD0Uzb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub
path = kagglehub.dataset_download("shivamb/netflix-shows")

import os

# The 'path' variable, after downloading, refers to the directory where the dataset is stored.
# pd.read_csv expects a file path, not a directory path.
# We need to find the actual CSV file within this downloaded directory.

# List files in the downloaded directory
files_in_dataset = os.listdir(path)

# Look for a CSV file. A common pattern for Kaggle datasets is that the main data is in one CSV.
csv_file = None
for file_name in files_in_dataset:
    if file_name.endswith(".csv"):
        csv_file = file_name
        break

if csv_file:
    full_csv_path = os.path.join(path, csv_file)
    datos = pd.read_csv(full_csv_path)
else:
    print(f"Error: No se encontró ningún archivo CSV en el directorio: {path}")
    datos = None

datos.info()

datos.head()

